/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Beer {
  'id' : bigint,
  'abv' : number,
  'ibu' : bigint,
  'onTap' : boolean,
  'name' : string,
  'description' : string,
  'style' : string,
}
export interface _SERVICE {
  'addBeer' : ActorMethod<[string, string, number, bigint, string], bigint>,
  'getAllBeers' : ActorMethod<[], Array<Beer>>,
  'getBeer' : ActorMethod<[bigint], Beer>,
  'getBeersByStatus' : ActorMethod<[boolean], Array<Beer>>,
  'getBeersByStyle' : ActorMethod<[string], Array<Beer>>,
  'removeBeer' : ActorMethod<[bigint], undefined>,
  'toggleOnTap' : ActorMethod<[bigint], undefined>,
  'updateBeer' : ActorMethod<
    [bigint, string, string, number, bigint, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];