/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Beer = IDL.Record({
  'id' : IDL.Nat,
  'abv' : IDL.Float64,
  'ibu' : IDL.Nat,
  'onTap' : IDL.Bool,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'style' : IDL.Text,
});

export const idlService = IDL.Service({
  'addBeer' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'getAllBeers' : IDL.Func([], [IDL.Vec(Beer)], ['query']),
  'getBeer' : IDL.Func([IDL.Nat], [Beer], ['query']),
  'getBeersByStatus' : IDL.Func([IDL.Bool], [IDL.Vec(Beer)], ['query']),
  'getBeersByStyle' : IDL.Func([IDL.Text], [IDL.Vec(Beer)], ['query']),
  'removeBeer' : IDL.Func([IDL.Nat], [], []),
  'toggleOnTap' : IDL.Func([IDL.Nat], [], []),
  'updateBeer' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Float64, IDL.Nat, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Beer = IDL.Record({
    'id' : IDL.Nat,
    'abv' : IDL.Float64,
    'ibu' : IDL.Nat,
    'onTap' : IDL.Bool,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'style' : IDL.Text,
  });
  
  return IDL.Service({
    'addBeer' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'getAllBeers' : IDL.Func([], [IDL.Vec(Beer)], ['query']),
    'getBeer' : IDL.Func([IDL.Nat], [Beer], ['query']),
    'getBeersByStatus' : IDL.Func([IDL.Bool], [IDL.Vec(Beer)], ['query']),
    'getBeersByStyle' : IDL.Func([IDL.Text], [IDL.Vec(Beer)], ['query']),
    'removeBeer' : IDL.Func([IDL.Nat], [], []),
    'toggleOnTap' : IDL.Func([IDL.Nat], [], []),
    'updateBeer' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Float64, IDL.Nat, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };